In [41]:
#Importo as bibliotecas
import pandas as pd

In [42]:
#Carrega as bases de produtos
dfProd = pd.read_csv("produtos.csv", delimiter=",")
dfProdMarca = pd.read_csv("produtos_sem_marca_corrigidos.csv", delimiter=",")
dfProdAdicional = pd.read_csv("Produto adicional.csv", delimiter=";")

In [43]:
#Apago a coluna "Marca" porque quado fazia o merge apareciam as colunas Marca_X e Marca_Y
dfProd = dfProd.drop(columns=["Marca"])
dfProd

    ID_Produto                   Nome_Produto         Categoria    Preco
0            1           Máquina de Lavar 8kg  Eletrodomésticos  1632.61
1            2  Smartphone Samsung Galaxy S21  Eletrodomésticos  3306.28
2            3         Notebook Dell Inspiron  Eletrodomésticos  1236.89
3            4                      TV LG 50"       Eletrônicos   170.47
4            5  Geladeira Brastemp Frost Free  Eletrodomésticos  3845.33
..         ...                            ...               ...      ...
94          95                Roteador D-Link            Móveis  1742.87
95          96              Smartwatch Huawei       Informática   428.38
96          97       Máquina de Costura Elgin            Móveis  4879.18
97          98             Ventilador Mondial            Móveis  4103.17
98          99             Cooktop Electrolux            Móveis  4277.48

[99 rows x 4 columns]

In [44]:
#Realizo o merge entre os dataFrames para pegar a coluna "Marca"
dfProdMerge = pd.merge(dfProd, dfProdMarca, left_on="ID_Produto", right_on="ID_Produto", how="inner")
dfProdMerge

,ID_Produto,Nome_Produto,Categoria,Preco,Marca
0,1,Máquina de Lavar 8kg,Eletrodomésticos,1632.61,Brastemp
1,2,Smartphone Samsung Galaxy S21,Eletrodomésticos,3306.28,Samsung
2,3,Notebook Dell Inspiron,Eletrodomésticos,1236.89,Dell
3,4,"TV LG 50""",Eletrônicos,170.47,LG
4,5,Geladeira Brastemp Frost Free,Eletrodomésticos,3845.33,Brastemp
...,...,...,...,...,...
94,95,Roteador D-Link,Móveis,1742.87,D-Link
95,96,Smartwatch Huawei,Informática,428.38,Huawei
96,97,Máquina de Costura Elgin,Móveis,4879.18,LG
97,98,Ventilador Mondial,Móveis,4103.17,Mondial
98,99,Cooktop Electrolux,Móveis,4277.48,Electrolux

In [46]:
#Incluo um valor 0.00 na coluna preço, porque estava vazio
dfProdAdicional["Preco"] = 0.00
dfProdAdicional

   ID_Produto Nome_Produto    Categoria  Preco  Marca
0         100       Mouse   Informática    0.0  Inova

In [47]:
#Concateno as bases em uma só
dfProdutos = pd.concat([dfProdMerge, dfProdAdicional], ignore_index=True)
dfProdutos

,ID_Produto,Nome_Produto,Categoria,Preco,Marca
0,1,Máquina de Lavar 8kg,Eletrodomésticos,1632.61,Brastemp
1,2,Smartphone Samsung Galaxy S21,Eletrodomésticos,3306.28,Samsung
2,3,Notebook Dell Inspiron,Eletrodomésticos,1236.89,Dell
3,4,"TV LG 50""",Eletrônicos,170.47,LG
4,5,Geladeira Brastemp Frost Free,Eletrodomésticos,3845.33,Brastemp
...,...,...,...,...,...
95,96,Smartwatch Huawei,Informática,428.38,Huawei
96,97,Máquina de Costura Elgin,Móveis,4879.18,LG
97,98,Ventilador Mondial,Móveis,4103.17,Mondial
98,99,Cooktop Electrolux,Móveis,4277.48,Electrolux
99,100,Mouse,Informática,0.00,Inova

In [48]:
#Exporto os dados para um arquivo CSV
dfProdutos.to_csv("dfProdutos.csv", sep=",", index=False)